### ISSUE TITLE
ModuleNotFoundError: No module named 'APDrawingGAN.options'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [shasph/dualFace#1]
**When I run the code**

![image](https://user-images.githubusercontent.com/57835828/119170916-2a64f280-ba79-11eb-9ca2-95255660027f.png)

**Explain how to fix the error ...**

**_Thank_**

**Comment by Huang-Zhengyu** [comment]
> **When I run the code**
> 
> ![image](https://user-images.githubusercontent.com/57835828/119170916-2a64f280-ba79-11eb-9ca2-95255660027f.png)
> 
> **Explain how to fix the error ...**
> 
> **_Thank_**

Please download from APDrawingGAN as follows:

https://github.com/yiranran/APDrawingGAN

and copy the code to APDrawingGAN folder.

**Comment by farzadmohseni-ir** [comment]
**We downloaded the package and extracted it in the mentioned folder :**

![image](https://user-images.githubusercontent.com/57835828/119254040-5a231000-bbc9-11eb-9ced-c3100b798dc3.png)

![image](https://user-images.githubusercontent.com/57835828/119254024-47a8d680-bbc9-11eb-9545-673670433230.png)

**&**

**The following error has occurred
Please help ...**

ModuleNotFoundError: No module named 'APDrawingGAN.data.face_landmark'

![image](https://user-images.githubusercontent.com/57835828/119254073-8a6aae80-bbc9-11eb-8477-d418e3bbc57d.png)

**Comment by shasph** [comment]
You should keep our files in the APDrawingGAN folder. 
-face_landmark.py
-train.py 

PS. To avoid this kind of confusion, we plan to embed the source code of APDrawingGAN in our archive soon. 
Thank you for your contact.

**Comment by bambi1202** [comment]
as the error mentioned that it did not find 'APDrawingGAN.data.face_landmark'. I think you should grab the **face_landmark.py** which currently under your _/APDrawingGAN_ folder into the _/APDrawingGAN/data_. Hope this can help.

**Comment by farzadmohseni-ir** [comment]
**It is discussed in this issue :**

**Error 1 )** ModuleNotFoundError: No module named 'APDrawingGAN.options'

**Corrected by : Download**   https://github.com/yiranran/APDrawingGAN   **& extracted it in the**  _./APDrawingGAN_  **folder**


**Error 2 )** ModuleNotFoundError: No module named 'APDrawingGAN.data.face_landmark'

**Corrected by :** **Move file location**  _face_landmark.py_  **from**  _./APDrawingGAN_  **folder to**  _./APDrawingGAN/data_ **folder**


**Error 3 )** ImportError: cannot import name 'Ui_Form' from 'ui.ui' (C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\ui\ui.py)

**Now how do I fix this error ⬆?
Help fix the error
Thanks**


![image](https://user-images.githubusercontent.com/57835828/119325123-d08d4400-bc95-11eb-9d72-94ec3a2db25a.png)

**Comment by farzadmohseni-ir** [comment]
> > **When I run the code**
> > ![image](https://user-images.githubusercontent.com/57835828/119170916-2a64f280-ba79-11eb-9ca2-95255660027f.png)
> > **Explain how to fix the error ...**
> > **_Thank_**
> 
> Please download from APDrawingGAN as follows:
> 
> https://github.com/yiranran/APDrawingGAN
> 
> and copy the code to APDrawingGAN folder.



> as the error mentioned that it did not find 'APDrawingGAN.data.face_landmark'. I think you should grab the **face_landmark.py** which currently under your _/APDrawingGAN_ folder into the _/APDrawingGAN/data_. Hope this can help.




### **It is discussed in this issue :**

**Error 1 )** ModuleNotFoundError: No module named 'APDrawingGAN.options'

**Corrected by : Download**   https://github.com/yiranran/APDrawingGAN   **& extracted it in the**  _./APDrawingGAN_  **folder**


**Error 2 )** ModuleNotFoundError: No module named 'APDrawingGAN.data.face_landmark'

**Corrected by :** **Move file location**  _face_landmark.py_  **from**  _./APDrawingGAN_  **folder to**  _./APDrawingGAN/data_ **folder**


**Error 3 )** ImportError: cannot import name 'Ui_Form' from 'ui.ui' (C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\ui\ui.py)

**Now how do I fix this error ⬆?
Help fix the error
Thanks**


![image](https://user-images.githubusercontent.com/57835828/119325123-d08d4400-bc95-11eb-9d72-94ec3a2db25a.png)

**Comment by bambi1202** [comment]
It seems that we have some missing files on our remote repo. We will make a further update ASAP. Thanks for your patient!

**Comment by bambi1202** [comment]
We had pushed a new version. Hope it fixed. 

> > > **When I run the code**
> > > ![image](https://user-images.githubusercontent.com/57835828/119170916-2a64f280-ba79-11eb-9ca2-95255660027f.png)
> > > **Explain how to fix the error ...**
> > > **_Thank_**
> > 
> > 
> > Please download from APDrawingGAN as follows:
> > https://github.com/yiranran/APDrawingGAN
> > and copy the code to APDrawingGAN folder.
> 
> > as the error mentioned that it did not find 'APDrawingGAN.data.face_landmark'. I think you should grab the **face_landmark.py** which currently under your _/APDrawingGAN_ folder into the _/APDrawingGAN/data_. Hope this can help.
> 
> ### **It is discussed in this issue :**
> **Error 1 )** ModuleNotFoundError: No module named 'APDrawingGAN.options'
> 
> **Corrected by : Download** https://github.com/yiranran/APDrawingGAN **& extracted it in the** _./APDrawingGAN_ **folder**
> 
> **Error 2 )** ModuleNotFoundError: No module named 'APDrawingGAN.data.face_landmark'
> 
> **Corrected by :** **Move file location** _face_landmark.py_ **from** _./APDrawingGAN_ **folder to** _./APDrawingGAN/data_ **folder**
> 
> **Error 3 )** ImportError: cannot import name 'Ui_Form' from 'ui.ui' (C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\ui\ui.py)
> 
> **Now how do I fix this error ⬆? Help fix the error Thanks**
> 
> ![image](https://user-images.githubusercontent.com/57835828/119325123-d08d4400-bc95-11eb-9d72-94ec3a2db25a.png)

**Comment by farzadmohseni-ir** [comment]
> We had pushed a new version. Hope it fixed.
> 
> > > > **When I run the code**
> > > > ![image](https://user-images.githubusercontent.com/57835828/119170916-2a64f280-ba79-11eb-9ca2-95255660027f.png)
> > > > **Explain how to fix the error ...**
> > > > **_Thank_**
> > > 
> > > 
> > > Please download from APDrawingGAN as follows:
> > > https://github.com/yiranran/APDrawingGAN
> > > and copy the code to APDrawingGAN folder.
> > 
> > 
> > > as the error mentioned that it did not find 'APDrawingGAN.data.face_landmark'. I think you should grab the **face_landmark.py** which currently under your _/APDrawingGAN_ folder into the _/APDrawingGAN/data_. Hope this can help.
> > 
> > 
> > ### **It is discussed in this issue :**
> > **Error 1 )** ModuleNotFoundError: No module named 'APDrawingGAN.options'
> > **Corrected by : Download** https://github.com/yiranran/APDrawingGAN **& extracted it in the** _./APDrawingGAN_ **folder**
> > **Error 2 )** ModuleNotFoundError: No module named 'APDrawingGAN.data.face_landmark'
> > **Corrected by :** **Move file location** _face_landmark.py_ **from** _./APDrawingGAN_ **folder to** _./APDrawingGAN/data_ **folder**
> > **Error 3 )** ImportError: cannot import name 'Ui_Form' from 'ui.ui' (C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\ui\ui.py)
> > **Now how do I fix this error ⬆? Help fix the error Thanks**
> > ![image](https://user-images.githubusercontent.com/57835828/119325123-d08d4400-bc95-11eb-9d72-94ec3a2db25a.png)



### Thank you very much for your guidance and help . But again the following error occurs .

**New Error )** TypeError: exceptions must derive from BaseException


https://user-images.githubusercontent.com/57835828/119436105-d08e5200-bd30-11eb-8e80-ca5a4a0007c4.mp4


Is it possible to connect to my system with [AnyDesk software](https://anydesk.com/en) _( This application is for desktop control of people from remote places )_ and teach me the run of this project ?
I have all the necessary libraries and directories in my system .
Please set a time for me to give you the address of _my AnyDesk_ to teach you how to run this project .
**Is it possible ?**

**Comment by bambi1202** [comment]
I have done some search on your new error. It seems that the python version does matter. We ran our project on python3.6 basically. I think it's better to rebuild a conda environment with python3.6 and run on it.

**Comment by farzadmohseni-ir** [comment]
I Run the project with Anaconda
But the following error occurs and cannot be fixed : 

**[Click : Error Link](https://www.screencast.com/t/MtVYHbiEyv0b)**

ModuleNotFoundError: No module named 'face_recognition'

&

I installed it from **[this link](https://pypi.org/project/face-recognition/)**
```python
pip install face-recognition
```


If possible, send me your email so that I can give you my AnyDesk ID to connect to my system and run the project , Please .

**_Thanks_**

**Comment by farzadmohseni-ir** [comment]
> I have done some search on your new error. It seems that the python version does matter. We ran our project on python3.6 basically. I think it's better to rebuild a conda environment with python3.6 and run on it.


I Run the project with Anaconda
But the following error occurs and cannot be fixed : 

**[Click : Error Link](https://www.screencast.com/t/MtVYHbiEyv0b)**

ModuleNotFoundError: No module named 'face_recognition'

&

I installed it from **[this link](https://pypi.org/project/face-recognition/)**
```python
pip install face-recognition
```


If possible, send me your email so that I can give you my AnyDesk ID to connect to my system and run the project , Please .

**_Thanks_**

**Comment by farzadmohseni-ir** [comment]
**Recorded video file of running all the steps** [Click Link](https://www.screencast.com/t/tgkx4dRcd)


**1 )** In the **first stage** run with Anaconda :

```
cd sse
sse.exe "-i index_file -v vocabulary -f filelist -n 8"
```

```
call conda activate py36df
python demo.py
```

_**Error :**_

> ImportError: numpy.core.multiarray failed to import
> Traceback (most recent call last):
>   File "demo.py", line 3, in <module>
>     import cv2
>   File "C:\Users\farza\.conda\envs\py36df\lib\site-packages\cv2\__init__.py", line 5, in <module>
>     from .cv2 import *
> ImportError: numpy.core.multiarray failed to import

![image](https://user-images.githubusercontent.com/57835828/119600616-a3a77100-bdfc-11eb-922a-25d8f9eefef2.png)


**2 )** In the **second stage** run with VSCode :

```
cd sse
sse.exe "-i index_file -v vocabulary -f filelist -n 8"
```
**_Error :_**
> sse.exe : The term 'sse.exe' is not recognized as the name of a         
> cmdlet, function, script file, or operable program. Check the spelling  
> of the name, or if a path was included, verify that the path is         
> correct and try again.
> At line:1 char:1
> + sse.exe "-i index_file -v vocabulary -f filelist -n 8"
> + ~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (sse.exe:String) [], Com  
>    mandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>
> Suggestion [3,General]: The command sse.exe was not found, but does exist in the current location. Windows PowerShell does > not load commands from the current location by default. If you trust this command, instead type: ".\sse.exe". See "get-help > > about_Command_Precedence" for more details.

**_+_**


```
call conda activate py36df
python demo.py
```
**_Error :_**
> Load sse list with length  518
> base-img imgdata/CelebAMask-HQ\16.jpg
> drawOriSkin= True
> QPixmap::fromImage: QPixmap cannot be created without a QGuiApplication 
> QPixmap: Must construct a QGuiApplication before a QPixmap


![image](https://user-images.githubusercontent.com/57835828/119600488-6347f300-bdfc-11eb-8fd3-53a22e535c12.png)

**_Help me get the Run Code .
Thanks_**
